# Generated by Django 5.2 on 2025-04-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(choices=[('AD', 'Adventure'), ('NT', 'Nature'), ('CH', 'Culture & History'), ('SH', 'Shopping'), ('BR', 'Beauty & Relax'), ('SP', 'Sports'), ('ET', 'Entertainment'), ('LS', 'Luxury')], default='AD', max_length=2),
        ),
    ]
