# Generated by Django 5.2 on 2025-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_feature_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='feature',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddField(
            model_name='city',
            name='feature',
            field=models.CharField(choices=[('AD', 'Adventure'), ('NT', 'Nature'), ('CH', 'Culture & History'), ('SH', 'Shopping'), ('BR', 'Beauty & Relax'), ('SP', 'Sports'), ('ET', 'Entertainment'), ('LS', 'Luxury')], default='AD', max_length=2),
        ),
    ]
