# Generated by Django 5.2 on 2025-04-30 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_city_feature_delete_feature_city_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='feature',
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AD', 'Adventure'), ('NT', 'Nature'), ('CH', 'Culture & History'), ('SH', 'Shopping'), ('BR', 'Beauty & Relax'), ('SP', 'Sports'), ('ET', 'Entertainment'), ('LS', 'Luxury')], default='AD', max_length=2)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.city')),
            ],
        ),
    ]
