# Generated by Django 5.2 on 2025-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_city_feature_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
