# Generated by Django 5.2 on 2025-05-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_category_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
