# Generated by Django 5.2 on 2025-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_place_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Nature', 'Nature'), ('Culture & History', 'Culture & History'), ('Shopping', 'Shopping'), ('Beauty & Relax', 'Beauty & Relax'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Luxury', 'Luxury')], default='Adventure', max_length=30),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('NT', 'Nature'), ('CH', 'Culture & History'), ('SH', 'Shopping'), ('ET', 'Entertainment'), ('FB', 'Food & Beverages')], default='Adventure', max_length=2),
        ),
    ]
