# Generated by Django 5.2 on 2025-05-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_feature_name_alter_place_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Culture & History', 'Culture & History'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Food & Beverages', 'Food & Beverages')], default='Adventure', max_length=20),
        ),
    ]
